### ISSUE TITLE
Mount netkit-fs-i386-F7.0

### ISSUE THREAD

**Issue by evaCastro** [netkit-ng/netkit-ng-core#7]
Hi,

I'm trying to mount the filesystem netkit-fs-i386-F7.0 but it seems it does not contain a valid partition table:

root~:# /sbin/fdisk -lu netkit-fs-i386-F7.0
...
Disk netkit-fs-i386-F7.0 doesn't contain a valid partition table

Thank you for your help.

eva

**Comment by kartoch** [comment]
Compared to original netkit, there is no partitions but only a simple ext2 fs, so you can mount it directly.
